[package]
name = "granularity-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28.6"
log = { workspace= true }
tokio = { workspace= true }
env_logger = { workspace = true }
wgpu = { workspace = true }
granularity = { workspace = true }
anyhow = { workspace = true }
