[package]
name = "granularity-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
wgpu = { workspace = true }
granularity = { workspace = true }
anyhow = { workspace = true }
cosmic-text = { workspace = true }

[dev-dependencies]
swash = { workspace = true }
bytemuck = { workspace = true }
env_logger = { workspace = true }
