[workspace]

members = [
    "shell",
    "text",
    "geometry"
]

[workspace.dependencies]
granularity = { path = "granularity" }

serde_tuple = "0.5.0"
serde = { version = "1.0.164", features = ["derive"] }
derive_more = "0.99.17"
log = "0.4.19"
env_logger = "0.10.0"
# TODO: Only select the features we need
tokio = { version = "1.29.1", features = ["full"] }
wgpu = "0.16.1"
anyhow = "1.0.71"
swash = "0.1.8"
bytemuck = { version = "1.13.1", features = ["derive"] }
bitflags = { version = "2.3.3" }
cgmath = "0.18.0"
